# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  db: 
    image: "mcr.microsoft.com/mssql/server"
    environment: 
      SA_PASSWORD: "Dit is geen sterk wachtwoord"
      ACCEPT_EULA: "Y"
    ports: 
      - 1433:1433
    volumes: 
      - c:\src\db\data:/var/opt/mssql/data
  project:
    image: project
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 5000:5000
      - 5001:5000
    depends_on: 
      - db
